version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch-es-101
    environment:
      - node.name=es101
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=90%
      - cluster.routing.allocation.disk.watermark.flood_stage=95%
      # CORS settings for both tools
      - http.cors.enabled=true
      - "http.cors.allow-origin=http://localhost:9280,http://localhost:9100"
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Accept
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana-es-101
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_STARTUPTIMEOUT=300000
    networks:
      - elastic
    depends_on:
      - elasticsearch

  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue-es-101
    ports:
      - 9280:8080
    networks:
      - elastic
    depends_on:
      - elasticsearch

  elasticsearch-head:
    image: tobias74/elasticsearch-head
    container_name: elasticsearch-head-es-101
    ports:
      - 9100:9100
    networks:
      - elastic
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge
